version: '2'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      TZ: America/Maceio
    ports:
      - 2181:2181/tcp

  kafka0:
    image: confluentinc/cp-kafka:5.3.1
    environment:
      BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER://kafka0:29092,LISTENER_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER:PLAINTEXT,LISTENER_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 2
      TZ: America/Maceio
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092/tcp

  kafdrop:
    image: obsidiandynamics/kafdrop
    environment:
      JVM_OPTS: -Xms32M -Xmx64M
      KAFKA_BROKERCONNECT: kafka0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      SERVER_SERVLET_CONTEXTPATH: /
      TZ: America/Maceio
    links:
      - kafka0:kafka0
      - zookeeper:zookeeper
    ports:
      - 9000:9000/tcp
